-- Filename: KCIs_01.sql
-- Description: KCI queries
-- Category: KCIs
-- Author: Sam Stephens
-- Last Updated: 2025-09-02

-- =====================
-- Query starts below
-- =====================

-- % of Transactions from Sanctioned Countries (Should be near 0 in real systems)
-- % of Inactive Risk Rules with Recent Alerts (If alerts are still being generated by inactive rules, that’s a control issue
-- # of Accounts Without Customer ID (Data integrity issue → failure in onboarding/KYC control)
-- % of Rules Not Triggering Alerts (Might signal outdated controls)
-- % of Alerts Without Follow-Up Action (Simulated — for example, alerts that are open for >30 days)
-- # of Transactions Missing Required Fields (Control over data quality (e.g., no amount, no transaction type))
-- % of High-Risk Countries Not Mapped to Any Rule (Gaps in your rule coverage)
-- Inactive Accounts with Transactions (Could indicate unauthorized activity or weak access control)
